### ISSUE TITLE
fIcy support for SSL streams?

### ISSUE THREAD

**Issue by sheffieldnikki** [wavexx/fIcy#1]
If I try to fetch a stream from an https:// site, I get the error:
fIcy: unknown protocol https

Thanks

**Comment by wavexx** [comment]
On Tue, Aug 09 2016, sheffieldnick notifications@github.com wrote:

> If I try to fetch a stream from an https:// site, I get the error:
> fIcy: unknown protocol https

fIcy is using his own protocol library, only supporting http 1.0 (with
basic auth) unfortunately.

I guess it wouldn't be too hard to wrap the I/O with Botan.
But I'm working on other projects right now, so patches welcome :)

**Comment by wavexx** [comment]
By the way, is the https url a public website I can try to use?

**Comment by sheffieldnikki** [comment]
I was trying to use [mixcloud.com](https://stream9.mixcloud.com/c/m4a/64/3/1/a/e/0eb9-2510-496b-8220-79f279509222.m4a) although they do actually provide a non-SSL version too.
