### ISSUE TITLE
When outputting tracklist, only first second of audio is recorded.

### ISSUE THREAD

**Issue by GeorgeL9** [wavexx/fIcy#2]
I want to record a stream and still see the metadata output in the terminal.

`./fIcy -o output.mp3 -d -t http://localhost:8000/stream`

The track updates come through just fine, but only the first 16kb of audio is written. If I run without the `-t` option, the whole audio records.

**Comment by wavexx** [comment]
On Fri, Jun 23 2017, George Lejnine wrote:
> I want to record a stream and still see the metadata output in the terminal.
>
> `./fIcy -o output.mp3 -d -t http://localhost:8000/stream`
>
> The track updates come through just fine, but only the first 8kb of
> audio is written. If I run without the `-t` option, the whole audio
> records.

Could you reproduce your issue on some public stream I can test?

**Comment by GeorgeL9** [comment]
Sure, here is my radio station: http://streaming.live365.com/a29103 (note, you need to be in the US to listen)

**Comment by wavexx** [comment]
MMh, I could connect from some EU countries, but not directly from an US address.

**Comment by GeorgeL9** [comment]
Here's a random station from iTunes radio that has this same issue:
http://192.99.34.205:8612/stream

**Comment by wavexx** [comment]
The fix was trivial enough. I don't think I ever tested this combination of flags.
Could you give it a try?

**Comment by GeorgeL9** [comment]
Worked perfectly. Thanks!

**Comment by wavexx** [comment]
On Fri, Jun 23 2017, George Lejnine wrote:
> Worked perfectly. Thanks!

I released 1.0.20 with this fix, since there still were some unreleased
changes pending since the last release.
