### ISSUE TITLE
Complaints from rpmlint

### ISSUE THREAD

**Issue by lgbaldoni** [wavexx/fIcy#3]
```
fIcy.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/fIcy
fIcy.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/fPls
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

[Ulrich Drepper](http://udrepper.livejournal.com/16116.html) can explain the issue much better than I could.

**Comment by wavexx** [comment]
As a side question, do you know of any stream that actually uses ipv6 addresses I could test?

**Comment by lgbaldoni** [comment]
> As a side question, do you know of any stream that actually uses ipv6 addresses I could test?

Alas, I do not.

**Comment by wavexx** [comment]
I pushed some changes to use getaddrinfo. Could you do some basic testing?

**Comment by lgbaldoni** [comment]
I ran very basic tests and things seem to be working, but I'm not a regular user so I could be missing things.

**Comment by wavexx** [comment]
On Sat, Feb 03 2018, Luigi Baldoni wrote:
> I ran very basic tests and things seem to be working, but I'm not a
> regular user so I could be missing things.

I was worried more about the build environment than anything else.
